### ISSUE TITLE
Could not resolve "qs"

### ISSUE THREAD

**Issue by mo2menelzeiny** [garridorafa/ra-strapi-v4-rest#1]
STEPS TO REPRODUCE

1. I installed the library
2. simple usage import and const provider = strapiRestProvider('http://localhost:1337')
3. I ran vite
4.  error

```
  VITE v4.2.1  ready in 831 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
✘ [ERROR] Could not resolve "qs"

    node_modules/ra-strapi-v4-rest/lib/index.js:20:37:
      20 │ const qs_1 = __importDefault(require("qs"));
         ╵                                      ~~~~

  You can mark the path "qs" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.
```

I fixed it by installing "qs"

doesn't this mean that you should move it from devdeps to deps in package.json?

**Comment by garridorafa** [comment]
Hello @mo2menelzeiny !
As you say, it is a "prod" dependency. Thank you for taking the time to report it!

it is solved in version [v1.0.0](https://github.com/garridorafa/ra-strapi-v4-rest/releases/tag/v1.0.0)
